const PRODUCTS_CACHE_KEY_PREFIX = 'products'
const PRODUCTS_LIST_CACHE_PREFIX = `${PRODUCTS_CACHE_KEY_PREFIX}:list:`
const PRODUCT_DETAIL_CACHE_PREFIX = `${PRODUCTS_CACHE_KEY_PREFIX}:detail:`
const TAXONOMY_CACHE_KEY = 'taxonomy:v2'
const ASSETS_CACHE_KEY = 'assets'
const SITE_CONTENT_CACHE_KEY = 'site-content:all'

module.exports = {
  PRODUCTS_CACHE_KEY_PREFIX,
  PRODUCTS_LIST_CACHE_PREFIX,
  PRODUCT_DETAIL_CACHE_PREFIX,
  TAXONOMY_CACHE_KEY,
  ASSETS_CACHE_KEY,
  SITE_CONTENT_CACHE_KEY,
}
